#!/bin/bash

# Clinical Paediatrics AI Chatbot - Quick Commands Reference
# Copy and paste these commands to deploy

echo "🚀 Clinical Paediatrics AI Chatbot - Deployment Commands"
echo "=========================================================="
echo ""
echo "Step 1: Test Locally"
echo "-------------------"
echo "npm install"
echo "npm run dev"
echo "# Open http://localhost:3000"
echo ""
echo "Step 2: Test Production"
echo "---------------------"
echo "npm run build"
echo "npm run preview"
echo "# Open http://localhost:4173"
echo ""
echo "Step 3: Push to GitHub"
echo "---------------------"
echo "git add ."
echo "git commit -m 'Deploy with Gemini API'"
echo "git push origin main"
echo ""
echo "Step 4: On Netlify"
echo "-----------------"
echo "1. Go to https://app.netlify.com"
echo "2. Click 'New site from Git'"
echo "3. Select your repo"
echo "4. Add environment variable:"
echo "   Key: VITE_GEMINI_API_KEY"
echo "   Value: AIzaSyAZQCA-ozuBD9qV6tAk577W_Q-A3U5cYew"
echo "5. Trigger deploy"
echo ""
echo "Your API Key:"
echo "AIzaSyAZQCA-ozuBD9qV6tAk577W_Q-A3U5cYew"
echo ""
echo "🎉 Done! Your app is live!"
